export const GET_ALL_TASKS_LOADING = "GET_ALL_TASKS_LOADING";
export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS";
export const GET_ALL_TASKS_FAILURE = "GET_ALL_TASKS_FAILURE";

export const GET_SINGLE_TASK_SUCCESS = "GET_SINGLE_TASK_SUCCESS";
export const RESET_SINGLE_TASK = "RESET_SINGLE_TASK";
